// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSq0ofVHfXg8l9aR7JrEo9dGz23mn6K10',
    appId: '1:1017361679305:web:9a855f10d29f5cd6179e18',
    messagingSenderId: '1017361679305',
    projectId: 'easy-parcel-d85dc',
    authDomain: 'easy-parcel-d85dc.firebaseapp.com',
    storageBucket: 'easy-parcel-d85dc.firebasestorage.app',
    measurementId: 'G-9T5FM8PWW2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpgD-vo4FNje85QMOq3x4ydY2gItJKGfQ',
    appId: '1:1017361679305:android:96c276257383e744179e18',
    messagingSenderId: '1017361679305',
    projectId: 'easy-parcel-d85dc',
    storageBucket: 'easy-parcel-d85dc.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDSq0ofVHfXg8l9aR7JrEo9dGz23mn6K10',
    appId: '1:1017361679305:web:3b48a260a7915c79179e18',
    messagingSenderId: '1017361679305',
    projectId: 'easy-parcel-d85dc',
    authDomain: 'easy-parcel-d85dc.firebaseapp.com',
    storageBucket: 'easy-parcel-d85dc.firebasestorage.app',
    measurementId: 'G-M5057QDHC5',
  );
}
